debug

diff --git a/backend-flask/bin/db-setup b/backend-flask/bin/db-setup
--- a/backend-flask/bin/db-setup
+++ b/backend-flask/bin/db-setup
@@ -1,8 +1,5 @@
-#! /usr/bin/bash
-
-echo "db-setup"
-
--e # stop if it fails at any point
+#!  /usr/bin/bash
+set -e # stop if it fails at any point
 
 CYAN='\033[1;36m'
 NO_COLOR='\033[0m'
@@ -11,7 +8,8 @@ printf "${CYAN}==== ${LABEL}${NO_COLOR}\n"
 
 bin_path="$(realpath .)/bin"
 
-source "$bin_path/db-drop"
-source "$bin_path/db-create"
-source "$bin_path/db-schema-load"
-source "$bin_path/db-seed"
+source "$bin_path/db/drop"
+source "$bin_path/db/create"
+source "$bin_path/db/schema-load"
+source "$bin_path/db/seed"
+source "$bin_path/db/update_cognito_user_ids"
